- name: "action: bug report"
  color: "#005AB0"
- name: "action: github issue"
  color: "#005AB0"
- name: "action: enhancement"
  color: "#005AB0"
  
- name: "type: bug"
  color: "#8D96A0"
- name: "type: github issue"
  color: "#8D96A0"
- name: "type: enhancement"
  color: "#8D96A0"
- name: "type: documentation"
  color: "#8D96A0"
- name: "type: discussion"
  color: "#8D96A0"
  
- name: "status: pending..."
  color: "#2D4938"
- name: "status: fixed"
  color: "#2D4938"
- name: "status: merged"
  color: "#2D4938"
- name: "status: unplanned"
  color: "#2D4938"
- name: "status: stale"
  color: "#472D2A"
- name: "status: unplanned"
  color: "#2D4938"
- name: "status: duplicate"
  color: "#2D4938"
- name: "status: implemented"
  color: "#2D4938"
