name: Close Milestone on Release

on: release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Close milestone 
      uses: adlerhsieh/prepare-release@0.1.2
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO_OWNER: ${{ github.repository_owner }}
        REPO: expr-6-Maki-Bundle-
        IGNORE_MILESTONE_NOT_FOUND: true
  